# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        chain_provider:
            chain:
                providers: [in_memory, teacher_db, student_db]
        in_memory:
            memory:
                users:
                    admin:
                        password: $2y$12$PWC8p2se7v.EjSO9Kjb/6.4QsNnyGgGDkLmdN8sCa.brObQJo2as2
                        roles: 'ROLE_ADMIN'
        student_db:
            entity: 
                class: AppBundle\Entity\Student
                property: email
        teacher_db:
            entity: 
                class: AppBundle\Entity\Teacher 
                property: email
                                     
    encoders:
        AppBundle\Entity\Teacher:
            algorithm: bcrypt
            cost: 12
        AppBundle\Entity\Student:
            algorithm: bcrypt
            cost: 12
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12
            
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                username_parameter: _email
            logout:
                path:   /logout
                target: /
                      
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/dashboard, roles: ROLE_Teacher }
        
